name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set lowercase repository name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
            --build-arg DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
            -t ghcr.io/${REPO_NAME}:latest .
          
          docker push ghcr.io/${REPO_NAME}:latest
